# SUPPORT_OBJS := 

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

COMMON_SRC = runtime-inline-asm.S
# START = ./getput-start.o

# uncomment if you want it to automatically run.
RUN=1

PROGS = runtime-inline.c

include $(CS140E_2023_PATH)/libpi/mk/Makefile.template-v2


