// 3-139
XX(PMU_RET_MISPREDICTED,    0x26, "return mispredicted")
XX(PMU_RET_PREDICTED,       0x25, "return predicted")
XX(PMU_RET_CNT,             0x24, "return count")
XX(PMU_CALL_CNT,            0x23, "call count")
XX(PMU_TLB_MISS,            0x16, "TLB miss")
XX(PMU_WBACK_DRAINED,       0x12, "writeback drained (stall?)")
XX(PMU_EXPLICIT_DATA_ACCESS,0x10, "explicit data access")
XX(PMU_DCACHE_MISS,         0xB,  "dcache miss")
XX(PMU_INST_CNT,            0x7,  "instruction count")
XX(PMU_BRANCH_MISPREDICT,   0x6,  "branch mispredict")
XX(PMU_BRANCH_EXECUTED,     0x5,  "branch executed")
XX(PMU_DATA_MICROTLB_MISS,  0x4,  "data microtlb miss")
XX(PMU_INST_MICROTLB_MISS,  0x3,  "instruction microtlb miss")
XX(PMU_DATA_STALL,          0x2,  "data stall")
XX(PMU_INST_STALL,          0x1,  "instruction stall")
XX(PMU_ICACHE_MISS,         0x0,  "icache miss")
XX(PMU_CYCLE_CNT,           0xff, "cycle count")
