
PROGS = fp-example.c
USE_FP=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

# uncomment if you want it to automatically run.
RUN=1

LIBS += $(LIBM)


#LIBS += ./libgcc.a
#LIB_POST := ./libgcc.a

include $(CS240LX_2023_PATH)/libpi/mk/Makefile.template-v2
